[project]
name = "sgaa"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "psycopg2>=2.9.10",
    "sqlmodel[postgresql]>=0.0.22",
    "uvicorn>=0.34.0",
]
